/**
 * Shopping List API Request and Response Types
 *
 * Type definitions for the shopping list AI-powered features API endpoints.
 * These types ensure type safety for client-server communication.
 */
import { PurchaseRecord, PurchasedItem } from './index';

// ============================================
// Request Types
// ============================================

/**
 * Request body for generating a shopping list from a user prompt
 * POST /api/shopping-list/generate
 */
export interface GenerateListRequest {
  /** User's shopping list request/prompt (e.g., "groceries for the week") */
  prompt: string;
}

/**
 * Request body for parsing an NFe (Brazilian electronic invoice)
 * POST /api/shopping-list/parse-nfe
 */
export interface ParseNFeRequest {
  /** URL of the Brazilian electronic invoice to parse */
  nfeUrl: string;
}

/**
 * Request body for generating AI insights from purchase history
 * POST /api/shopping-list/insights
 */
export interface GenerateInsightsRequest {
  /** Array of past purchase records to analyze */
  purchaseHistory: PurchaseRecord[];
}

// ============================================
// Response Types
// ============================================

/**
 * Response from shopping list generation endpoint
 * POST /api/shopping-list/generate
 */
export interface GenerateListResponse {
  /** Array of shopping list item names generated by AI */
  items: string[];
  /** Suggested title for the shopping list (typically same as prompt) */
  title: string;
}

/**
 * Response from NFe parsing endpoint
 * POST /api/shopping-list/parse-nfe
 */
export interface ParseNFeResponse {
  /** Name of the store from the invoice */
  storeName: string;
  /** Purchase date in ISO 8601 format */
  purchaseDate: string;
  /** Total amount of the purchase */
  totalAmount: number;
  /** Array of items purchased */
  items: PurchasedItem[];
}

/**
 * Response from insights generation endpoint
 * POST /api/shopping-list/insights
 */
export interface GenerateInsightsResponse {
  /** Markdown-formatted insights about spending patterns and savings opportunities */
  insights: string;
}

/**
 * Standard error response for all shopping list API endpoints
 */
export interface ErrorResponse {
  /** Machine-readable error code for programmatic handling */
  error: string;
  /** Human-readable error message for display to users */
  message: string;
  /** Optional technical details (only included in development mode) */
  details?: string;
}

// ============================================
// Type Guards
// ============================================

/**
 * Type guard to check if a response is an error response
 */
export function isErrorResponse(response: any): response is ErrorResponse {
  return typeof response === 'object' && response !== null && 'error' in response && 'message' in response;
}

/**
 * Type guard to check if a response is a successful GenerateListResponse
 */
export function isGenerateListResponse(response: any): response is GenerateListResponse {
  return (
    typeof response === 'object' &&
    response !== null &&
    'items' in response &&
    Array.isArray(response.items) &&
    'title' in response &&
    typeof response.title === 'string'
  );
}

/**
 * Type guard to check if a response is a successful ParseNFeResponse
 */
export function isParseNFeResponse(response: any): response is ParseNFeResponse {
  return (
    typeof response === 'object' &&
    response !== null &&
    'storeName' in response &&
    'purchaseDate' in response &&
    'totalAmount' in response &&
    'items' in response &&
    Array.isArray(response.items)
  );
}

/**
 * Type guard to check if a response is a successful GenerateInsightsResponse
 */
export function isGenerateInsightsResponse(response: any): response is GenerateInsightsResponse {
  return (
    typeof response === 'object' && response !== null && 'insights' in response && typeof response.insights === 'string'
  );
}
