import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PDFShoppingListItem {
  product_name: string;
  quantity: number;
  unit?: string;
  estimated_price?: number;
  category?: string;
  subcategory?: string;
}

export interface PDFShoppingListOptions {
  title: string;
  category: string;
  items: PDFShoppingListItem[];
  estimatedTotal: number;
  generatedByAI?: boolean;
  generatedDate?: string;
}

/**
 * Generate a PDF shopping list with checkboxes
 * @param options - Shopping list configuration
 * @returns PDF blob
 */
export function generateShoppingListPDF(options: PDFShoppingListOptions): Blob {
  const { title, category, items, estimatedTotal, generatedByAI = false, generatedDate } = options;

  // Create PDF document (A4, portrait)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  // ============================================
  // HEADER
  // ============================================

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 20);

  // Category badge
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const categoryLabel = getCategoryLabel(category);
  const categoryBadgeWidth = doc.getTextWidth(categoryLabel) + 8;
  doc.setFillColor(59, 130, 246); // Blue color
  doc.roundedRect(margin, 25, categoryBadgeWidth, 7, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.text(categoryLabel, margin + 4, 30);

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // AI badge (if generated by AI)
  if (generatedByAI) {
    const aiBadgeX = margin + categoryBadgeWidth + 5;
    const aiBadgeText = '🤖 Gerada por IA';
    const aiBadgeWidth = doc.getTextWidth(aiBadgeText) + 8;
    doc.setFillColor(147, 51, 234); // Purple color
    doc.roundedRect(aiBadgeX, 25, aiBadgeWidth, 7, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text(aiBadgeText, aiBadgeX + 4, 30);
    doc.setTextColor(0, 0, 0);
  }

  // Date
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const dateText = generatedDate || new Date().toLocaleDateString('pt-BR');
  doc.text(`Data: ${dateText}`, pageWidth - margin, 30, { align: 'right' });

  // Divider line
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, 36, pageWidth - margin, 36);

  // ============================================
  // ITEMS BY CATEGORY
  // ============================================

  let yPosition = 45;

  // Group items by category
  const itemsByCategory = items.reduce(
    (acc, item) => {
      const cat = item.category || 'Outros';
      if (!acc[cat]) {
        acc[cat] = [];
      }
      acc[cat].push(item);
      return acc;
    },
    {} as Record<string, PDFShoppingListItem[]>,
  );

  // Sort categories
  const sortedCategories = Object.keys(itemsByCategory).sort();

  // Track if we need a new page
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - 30) {
      doc.addPage();
      yPosition = 20;
      return true;
    }
    return false;
  };

  // Render each category
  for (const categoryName of sortedCategories) {
    const categoryItems = itemsByCategory[categoryName];

    checkPageBreak(15);

    // Category header
    doc.setFillColor(245, 245, 245);
    doc.rect(margin, yPosition - 5, pageWidth - 2 * margin, 8, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(categoryName, margin + 3, yPosition);
    yPosition += 10;

    // Group items by subcategory within this category
    const itemsBySubcategory = categoryItems.reduce(
      (acc, item) => {
        const subcat = item.subcategory || '';
        if (!acc[subcat]) {
          acc[subcat] = [];
        }
        acc[subcat].push(item);
        return acc;
      },
      {} as Record<string, PDFShoppingListItem[]>,
    );

    // Render subcategories
    for (const [subcategoryName, subcategoryItems] of Object.entries(itemsBySubcategory)) {
      if (subcategoryName) {
        checkPageBreak(8);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bolditalic');
        doc.setTextColor(100, 100, 100);
        doc.text(subcategoryName, margin + 5, yPosition);
        doc.setTextColor(0, 0, 0);
        yPosition += 6;
      }

      // Render items
      for (const item of subcategoryItems) {
        checkPageBreak(10);

        // Draw checkbox (4x4mm)
        doc.setLineWidth(0.3);
        doc.setDrawColor(100, 100, 100);
        doc.rect(margin + 7, yPosition - 3, 4, 4);

        // Item text
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const itemText = `${item.product_name}`;
        doc.text(itemText, margin + 14, yPosition);

        // Quantity
        const quantityText = `${item.quantity} ${item.unit || 'un'}`;
        doc.setFont('helvetica', 'bold');
        doc.text(quantityText, pageWidth - margin - 40, yPosition);

        // Price
        if (item.estimated_price !== undefined) {
          const priceText = formatCurrency(item.estimated_price * item.quantity);
          doc.setTextColor(0, 128, 0);
          doc.text(priceText, pageWidth - margin, yPosition, { align: 'right' });
          doc.setTextColor(0, 0, 0);
        }

        yPosition += 7;
      }

      yPosition += 2; // Space after subcategory
    }

    yPosition += 3; // Space after category
  }

  // ============================================
  // FOOTER
  // ============================================

  // Position footer at bottom of last page
  const footerY = pageHeight - 20;

  // Total box
  doc.setFillColor(59, 130, 246); // Blue
  doc.roundedRect(margin, footerY - 8, pageWidth - 2 * margin, 12, 2, 2, 'F');

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('Total Estimado:', margin + 5, footerY);
  doc.setFontSize(14);
  doc.text(formatCurrency(estimatedTotal), pageWidth - margin - 5, footerY, { align: 'right' });

  // Horizon AI watermark
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(150, 150, 150);
  doc.text('Gerado por Horizon AI', pageWidth / 2, pageHeight - 5, { align: 'center' });

  // Convert to blob
  const pdfBlob = doc.output('blob');
  return pdfBlob;
}

/**
 * Format currency in BRL
 */
function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  }).format(amount);
}

/**
 * Get category label in Portuguese
 */
function getCategoryLabel(category: string): string {
  const labels: Record<string, string> = {
    pharmacy: 'Farmácia',
    groceries: 'Mercearia',
    supermarket: 'Supermercado',
    restaurant: 'Restaurante',
    fuel: 'Combustível',
    retail: 'Varejo',
    services: 'Serviços',
    other: 'Outros',
  };
  return labels[category] || category;
}

/**
 * Download PDF file
 */
export function downloadPDF(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
